FROM centos:centos7.2.1511

# Install dependencies
RUN yum -y install make gcc cc tar

# Install Redis
RUN \
  cd /tmp && \
  curl -O http://download.redis.io/releases/redis-4.0.11.tar.gz && \
  tar xvzf redis-4.0.11.tar.gz && \
  cd redis-4.0.11 && \
  make && \
  make install && \
  cp -f src/redis-sentinel /usr/local/bin && \
  mkdir -p /etc/redis && \
  cp -f *.conf /etc/redis && \
  rm -rf /tmp/redis-4.0.11* && \
  sed -i 's/^\(bind .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(daemonize .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(dir .*\)$/# \1\ndir \/data/' /etc/redis/redis.conf && \
  sed -i 's/^\(protected-mode .*\)$/protected-mode no/' /etc/redis/redis.conf && \
  sed -i 's/^\(logfile .*\)$/# \1/' /etc/redis/redis.conf

# Cleanup dependencies
RUN yum -y erase gcc cc tar

# Define mountable directories
VOLUME ["/data"]

# Define working directory
WORKDIR /data

# Define entrypoint
ENTRYPOINT ["redis-server", "/etc/redis/redis.conf"]

# Expose ports
EXPOSE 6379

