- hosts: linux
  remote_user: root                         
  tasks:
    - name: Linux Server Installation MangoDb
      command: '/root/ci/installation/mongodbInstall.sh -s //192.168.33.101/US_Package/8.0_stable/2019-03-26-1/DEV/MongoRpm localhost rs -d'
